version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2024.01.2
      docker_layer_caching: true

    steps:
      - checkout
      - run: python3 -m venv .venv
      - run: . .venv/bin/activate && make deps
      - run: . .venv/bin/activate && make lint
      - run: . .venv/bin/activate && make test
      - run: make docker_build
      - run: make docker_push

workflows:
  basic:
    jobs:
      - build-and-test

