version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:2023.07.1

    steps:
      - checkout
      - run: make deps
      - run: make test

workflows:
  basic:
    jobs:
      - build-and-test

